### ISSUE TITLE
Functional Requirements Tracking

### ISSUE THREAD

**Issue by arlyon** [dragorhast/submission#19]
### Must
- [x] Customer must be able to unlock a bike through the app 
- [x] Customer must be able to rent a bike between pick-up points 
- [x] Customer must be able to report if a bike is damaged or broken 
- [x] Customer must be able to reserve a bike from a pick-up point 
- [x] Customer must be able to cancel current rental if issues arise 
- [x] Manager must be able bike status for a pick-up point
- [x] Manager must be able see all broken bikes
- [x] Manager must be able see all open issues
- [x] Manager must be able to view current reservations
- [x] Manager must be able to get daily report about bikes
- INVALID System must notify customer of reservation changes
- [x] System must generate report of “statistics” for each day 
- [x] System must not rent out broken or reserved bikes
- [x] System must be able to track status of all bikes
- [x] Operators must be able to take bikes in and out of circulation 
- [x] Operators must be able to change the status of a bike
- [x] Operators must be able to resolve and edit bike issues 
- [x] Operators must be able to report issues about a bike
- [x] Operators must be able to see locations and statuses of bikes

### Should
- [ ] Customer should be able to cancel a reservation beforehand 
- [ ] Customer should be able to apply for a refund
- [x] Customer should be able to return the bike to any locations 
- [x] Manager should be able to compare usage of various locations 
- INVALID Manager should be able to send messages to active customers
- [x] System should track location of all equipment 
- [x] Bike should be able to talk to system
- [x] Bike should send alarm if moved whilst locked 
- [x] Bike should have light for id in field
- [x] Bike should have QR code for id
- [x] Bike should have a lock that can be unlocked by customer
- INVALID Certain pickup points should allow for bespoke bike rental 
- INVALID Customer should be able to get equipment from shops
- INVALID Customer should be able to get a bespoke bike from shops

### Could
- [x] Customer could be able to lock bike during rental time 
- [x] Customer could be able to give general feedback 
- [ ] Customers could be able to subscribe for monthly usage 
- [ ] Customers could be able to do a group booking
- [ ] Manager could be able to change bookings
- [ ] System could adjust prices based on crime
- [ ] System could adjust prices based on traffic
- [ ] System could be usable in many languages
- [ ] System could predict maintenance using statistical models 
- [ ] System could perform sentiment analysis on complaints

**Comment by arlyon** [comment]
### Sprint 1
- starting a rental
- rental updates
- bike connectivity
- bike location updates
- bike communication
- user CRUD
- rental CRUD
- API schema defined

**Comment by arlyon** [comment]
### Sprint 2

...

**Comment by ssp6** [comment]
### Front End

### Must
* [x]  Customer must be able to unlock a bike through the app
* [x]  Customer must be able to rent a bike between pick-up points
* [x]  Customer must be able to report if a bike is damaged or broken
* [x]  Customer must be able to reserve a bike from a pick-up point
* [ ]  Customer must be able to cancel current rental if issues arise
* [x]  Manager must be able bike status for a pick-up point
* [x]  Manager must be able see all broken bikes
* [x]  Manager must be able see all open issues
* [x]  Manager must be able to view current reservations
* [ ]  Manager must be able to get daily report about bikes
* [ ]  System must notify customer of reservation changes
* [ ]  System must generate report of “statistics” for each day
* [x]  System must not rent out broken or reserved bikes
* [x]  System must be able to track status of all bikes
* [ ]  Operators must be able to take bikes in and out of circulation Operators must be able to change the status of a bike
* [x]  Operators must be able to resolve and edit bike issues
* [x]  Operators must be able to report issues about a bike
* [x]  Operators must be able to see locations and statuses of bikes

### Should
* [ ]  Customer should be able to cancel a reservation beforehand
* [ ]  Customer should be able to apply for a refund
* [x]  Customer should be able to return the bike to any locations
* [ ]  Manager should be able to compare usage of various locations
* [ ]  Manager should be able to send messages to active customers
* [x]  System should track location of all equipment
* [x]  Bike should be able to talk to system
* [ ]  Bike should send alarm if moved whilst locked
* [ ]  Bike should have light for id in field
* [x]  Bike should have QR code for id
* [x]  Bike should have a lock that can be unlocked by customer
* [ ]  Certain pickup points should allow for bespoke bike rental
* [ ]  Customer should be able to get equipment from shops
* [ ]  Customer should be able to get a bespoke bike from shops

### Could
* [x]  Customer could be able to lock bike during rental time
* [x]  Customer could be able to give general feedback
* [ ]  Customers could be able to subscribe for monthly usage
* [ ]  Customers could be able to do a group booking
* [ ]  Manager could be able to change bookings
* [ ]  System could adjust prices based on crime
* [ ]  System could adjust prices based on traffic
* [ ]  System could be usable in many languages
* [ ]  System could predict maintenance using statistical models
* [ ]  System could perform sentiment analysis on complaints
