### ISSUE TITLE
Non-Functional Requirements Tracking

### ISSUE THREAD

**Issue by arlyon** [dragorhast/submission#20]
### Must
- [x] App must make minimal web requests to the server
- [x] Server must be up with 99% availability
- [x] App must never crash outright, preferring to display errors and recover
- [x] All errors must be logged and reported to developers
- [x] Bikes will have an expected service time of about 3 months, and lifespan of 2 years
- [x] System must use strong cryptographic protocols (TLS 1.3) when transmitting sensitive data
- [x] System must securely store all personally identifiable information
- [x] System must otherwise adhere to industry best practices
- [x] System must comply (to the best of our non-legal-minded ability) with GDPR
- [x] Code must be installable with minimal effort 
- [x] System must keep regular backups
- [x] The system must have reversible transactions
- [x] User should be able to perform 90% of tasks in 10 clicks or less
- [x] App must be accessible on mobile and desktop

### Should
- [x] App should function fast on all browsers and devices 
- [x] User should be able to go from install to rental in 1 minute
- [x] Code should follow best practices
- [x] System should be automatically tested with CI/CD 
- [x] System should have 80% test coverage
- [x] System should have proportional capacity for bikes: 1,000 based on London figures of one bike per 1,000 residents
- [ ] App should keep TTI to below 2s on mobile
- [ ] Server should be capable of being placed behind a load- balancer
- [x] App will be available (with limited functionality) offline

### Could
- [x] App could use bundle splitting to improve FP
- [ ] App could keep FID to below 100ms on mobile
- [x] System could have capacity for a medium/large city (1,000,000 pop) and able to expand to others independently
- [x] Code could be well documented
- [ ] App could be audited for accessibility
