### ISSUE TITLE
Project Decisions and Plan

### ISSUE THREAD

**Issue by ssp6** [dragorhast/submission#3]
By this stage the group must have decided on key issues such as which software to use; which software process to use; how the complete product will be divided into sub-systems (top level design); how the software will be assessed for usability, technical correctness and customer expectations; what each student expects to contribute to the project; and how the group intend to collaborate. Provide details of these key issues.

- [x] Software: 
  - server: python
  - clients: javascript
  - embedded: python
  - site: html
- [x] Processes
  - git, github, agile-ish
- [x] high level architecture https://www.draw.io/#G196pmsdbEhEDNhgbd9SdgolZfmPjQq1KD
- [x] how to assess progress
  - usability
  - technical correctness
  - customer expectations
- [x] what each student is contributing
- [x] how to collaborate

**Comment by ssp6** [comment]
## Software Decisions

On a high level, the system is split into three components with some sub-components in each of the primary components. The three components are as follows:

### Server
The server is going to exclusively provide RESTful json endpoints for use by the web and mobile apps. Using python, asyncio, and aiohttp this high-performing server will be optimised for an io-bound workload. Using `async` in python allows the server to handle multiple network connections at once with ease. Additionally, asyncio renders realtime communication trivial with the support of websockets allowing any 2 way communication such as chat, realtime updates, push notifications, etc. to be implemented with ease.

### App Client
The app will leverage react and react-native to target web and cross-platform mobile with a single codebase allowing us to build rich, consistent, UI experiences no matter the interaction method. The same components will be used on mobile and on web allowing a "build once, deploy anywhere" approach.

### Embedded Client
The embedded client is what connects the system to the physical bikes. Equipped with a GPS/GPRS module, an RPi Zero W will provide constant connectivity with a central server giving the current location of every bike in the network. This is what allows the key value proposition of the system: no fixed rental / dropoff points. Anyone can rent from anywhere to anywhere.

**Comment by ssp6** [comment]
## Team Processes

We are using a agile-style continuous delivery approach where our team builds features in separate branches and uses github pull requests as a platform for feedback, evaluation, and testing before the branch is merged back into the master and automatically deployed immediately. This requires a rigorous and merciless continuous integration broker to automatically build every proposed version of the code and provide style feedback, run unit tests, do static analysis, and check for security problems. It complements test driven development very well ensuring regressions are impossible due to the fact that it is impossible to push code that breaks any previous tests.

Taking this approach reduces the barrier between developer and deployment to near-zero meaning anyone can (after a code review) push code immediately into the field.

To enable this, we are making use of Github's "issues" and "milestones" features to manage each sprint which are then worked on transparently and deployed as they are completed before we reconvene for the next sprint.

**Comment by ssp6** [comment]
## Assessment
Beyond our automated and rigorous software testing for ensuring technical correctness, we have a number of systems in place to measure other important factors:

### Usability @ssp6 have a look at this?
Our goal for usability is to create an app that requires no conscious thought to use. To achieve this, we plan on building our app with a few "waves" going from high level structure to component-by-component feedback. Each wave will have an iteration, a feedback session, and a second iteration. Our development process is centered around instantaneous iteration cycles and a feature of this is our ability to react very quickly to feedback.

The **first wave** centers around static mock-ups. Focusing on the basic flow of the application these coarse prototypes will establish the correct metaphors and patterns to use when developing the first interactive model. The feedback from this session is then used in the first version of the app.

The **second wave** consists of general layout and transition between the primary states of the application such as "looking for bike", "approaching bike", "administration", etc. This round will be used to determine what the important information is and how to display and transition between it intuitively. 

The **third wave** handles the individual components and their interaction with one another. For developing the UI we will use a library called [storybook](https://github.com/storybooks/storybook) which allows us to develop, iterate, and test individual components or views of our UI separately, making granular usability testing possible on a component-by-component basis.

### Customer Expectations

Measuring customer expectations is handled by ensuring each of our requirements is an actionable feature and maintaining a backlog of incomplete features still to be addressed. That means that the feature list is locked at the beginning and the scope remains fixed to the same scope the customer agreed on at the start of the project.

**Comment by ssp6** [comment]
## Contributing

We have a number of differently balanced members on the team, with interests ranging from planning and management, to UI/UX, embedded hardware, API design, architecture, high performance computing, data science, and CI/CD/devops.

Between us we have around two people handling each area with the more experienced developers able to hop between teams and help with design decisions, avoiding antipatterns, etc.

The development is spread across a number of repositories on github, one for each individual domain: server, app, embedded.

**Comment by ssp6** [comment]
## Iterations

### Stage 1 - Location to Location Rental

This first version will have no requirement on the hardware module allowing people to go to a location, rent an available bike, and drop it off at another location. Included with this version will be:

- location to location rental
- basic pricing system
- basic admin reports about bike usage
- basic user complaints / damage reports
- authentication and billing system

### Stage 2 - Location to anywhere

The next iteration of the software introduces a hardware module that will enable a user to pick up and drop off bikes from anywhere, removing the need for formal locations in the traditional sense rendering them little more than a branded bike rack. Included with this version:

- location to anywhere rental
- pricing influenced by crime / financial status / distance
- locations defined purely by geofences
- "unlimited" rental passes
- impounding for irresponsible parking

### Stage 3 - todo

...

**Comment by ssp6** [comment]
> ### Usability @ssp6 have a look at this?
> Our goal for usability is to create an app that requires no conscious thought to use. To achieve this, we plan on building our app with a few "waves" going from high level structure to component-by-component feedback. Each wave will have an iteration, a feedback session, and a second iteration. Our development process is centered around instantaneous iteration cycles and a feature of this is our ability to react very quickly to feedback.
> 
> The **first wave** centers around static mock-ups. Focusing on the basic flow of the application these coarse prototypes will establish the correct metaphors and patterns to use when developing the first interactive model. The feedback from this session is then used in the first version of the app.
> 
> The **second wave** consists of general layout and transition between the primary states of the application such as "looking for bike", "approaching bike", "administration", etc. This round will be used to determine what the important information is and how to display and transition between it intuitively.
> 
> The **third wave** handles the individual components and their interaction with one another. For developing the UI we will use a library called [storybook](https://github.com/storybooks/storybook) which allows us to develop, iterate, and test individual components or views of our UI separately, making granular usability testing possible on a component-by-component basis.


-----


@arlyon its very well written that's for sure haha.

Not positive on the difference between wave 1 and wave 2 though. Is it just stating that we're going to design the flow -> then design layout of those pages -> then make in react?

**Comment by arlyon** [comment]
Basically static mockups to animated mockups to react. Move things around to match what your plans are I just had a stream of ideas I needed to get down
